### ISSUE TITLE
Message is not a valid SOFA type

### ISSUE THREAD

**Issue by noxonsu** [tokenbrowser/token-app-js#11]
Just fork main app and deploy to heroku. then click on "deploy" tab > connect repository > click "deply".  App crashed when resive first message from user. 
```
Message is not a valid SOFA type
 /app/src/lib/Logger.js:19
     Logger.log(Logger.colorPrefix('\u21D2  ', wrap(sofa.string, {width: 60, cut: true}), chalk.yellow, chalk.grey));
                                                        ^

 TypeError: Cannot read property 'string' of null
     at Function.receivedMessage (/app/src/lib/Logger.js:19:56)
     at Session (/app/src/lib/Client.js:64:20)
     at execute (/app/src/lib/Session.js:122:7)
     at Query.client.query (/app/src/lib/Session.js:143:9)
     at Query.handleReadyForQuery (/app/node_modules/pg/lib/query.js:112:10)
     at Connection.<anonymous> (/app/node_modules/pg/lib/client.js:172:19)
     at emitOne (events.js:101:20)
     at Connection.emit (events.js:188:7)
     at Socket.<anonymous> (/app/node_modules/pg/lib/connection.js:121:12)
     at emitOne (events.js:96:13)
```

'sofa' is 'null' here ^

and 

``` 
wrapped.sofa  SOFA::Message:{"body":"Go"}
```
here: 
https://github.com/noxonsu/token-app-js/blob/master/src/lib/Client.js#L63

**Comment by noxonsu** [comment]
this bug appears only when using "deploy" option in heroku, but when i click to "deploy to heroku" my bot working fine  http://joxi.ru/MAj0laJCnBe3me 

may be it is bug on heroku side, not need to fix by you
