### ISSUE TITLE
Can no longer connect to the Signal Service

### ISSUE THREAD

**Issue by helloluis** [tokenbrowser/token-app-js#6]
Filed this in the Headless Client too (https://github.com/tokenbrowser/token-headless-client/issues/5).

Everything was working for a few hours yesterday when I was initially coding my app but now my app can't even connect to the Signal service anymore. My Heroku logs below:

```
2017-04-21T01:33:24.168861+00:00 app[headless-client.1]: [main] INFO org.bitcoinj.wallet.DeterministicKeyChain - Took 259.3 ms
2017-04-21T01:33:25.029897+00:00 app[headless-client.1]: ID Address: 0x85eec6286c17f8071015b5a9dc1050c44a47a73d
2017-04-21T01:33:25.031366+00:00 app[headless-client.1]: Wallet Address: 0x586c54019e3ac3abf81460879a74e53f573136c0
2017-04-21T01:33:29.410422+00:00 app[headless-client.1]: Registered with ID service as 'cryptopop'
2017-04-21T01:33:30.066017+00:00 app[headless-client.1]: Successfully updated avatar
2017-04-21T01:33:30.330082+00:00 app[headless-client.1]: onSubcribe 0x85eec6286c17f8071015b5a9dc1050c44a47a73d
2017-04-21T01:33:30.330180+00:00 app[headless-client.1]: onSubcribe 0x85eec6286c17f8071015b5a9dc1050c44a47a73d_rpc_request
2017-04-21T01:33:31.188192+00:00 app[headless-client.1]: org.whispersystems.signalservice.api.push.exceptions.PushNetworkException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: java.security.cert.CertPathBuilderException: No issuer certificate for certificate in certification path found.
2017-04-21T01:33:31.188309+00:00 app[headless-client.1]: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getConnection(PushServiceSocket.java:612)
2017-04-21T01:33:31.193287+00:00 app[headless-client.1]: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.makeRequest(PushServiceSocket.java:499)
2017-04-21T01:33:31.193359+00:00 app[headless-client.1]: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getAvailablePreKeys(PushServiceSocket.java:248)
2017-04-21T01:33:31.193427+00:00 app[headless-client.1]: 	at org.whispersystems.signalservice.api.SignalServiceAccountManager.getPreKeysCount(SignalServiceAccountManager.java:277)
2017-04-21T01:33:31.193480+00:00 app[headless-client.1]: 	at com.bakkenbaeck.token.headless.signal.Manager.init(Manager.java:222)
2017-04-21T01:33:31.193545+00:00 app[headless-client.1]: 	at com.bakkenbaeck.token.headless.TokenHeadlessClient.main(TokenHeadlessClient.java:193)
2017-04-21T01:33:31.193779+00:00 app[headless-client.1]: Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: java.security.cert.CertPathBuilderException: No issuer certificate for certificate in certification path found.
2017-04-21T01:33:31.193814+00:00 app[headless-client.1]: 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
2017-04-21T01:33:31.193889+00:00 app[headless-client.1]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
2017-04-21T01:33:31.193852+00:00 app[headless-client.1]: 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
2017-04-21T01:33:31.193928+00:00 app[headless-client.1]: 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
2017-04-21T01:33:31.194073+00:00 app[headless-client.1]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1514)
2017-04-21T01:33:31.194150+00:00 app[headless-client.1]: 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
2017-04-21T01:33:31.194211+00:00 app[headless-client.1]: 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1026)
2017-04-21T01:33:31.194270+00:00 app[headless-client.1]: 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:961)
2017-04-21T01:33:31.194324+00:00 app[headless-client.1]: 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
2017-04-21T01:33:31.194387+00:00 app[headless-client.1]: 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
2017-04-21T01:33:31.194692+00:00 app[headless-client.1]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
2017-04-21T01:33:31.194750+00:00 app[headless-client.1]: 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
2017-04-21T01:33:31.194829+00:00 app[headless-client.1]: 	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:241)
2017-04-21T01:33:31.194891+00:00 app[headless-client.1]: 	at com.squareup.okhttp.Connection.connect(Connection.java:158)
2017-04-21T01:33:31.194975+00:00 app[headless-client.1]: 	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
2017-04-21T01:33:31.195042+00:00 app[headless-client.1]: 	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
2017-04-21T01:33:31.195256+00:00 app[headless-client.1]: 	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
2017-04-21T01:33:31.195338+00:00 app[headless-client.1]: 	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
2017-04-21T01:33:31.195381+00:00 app[headless-client.1]: 	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
2017-04-21T01:33:31.195437+00:00 app[headless-client.1]: 	at com.squareup.okhttp.Call.getResponse(Call.java:262)
2017-04-21T01:33:31.195511+00:00 app[headless-client.1]: 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
2017-04-21T01:33:31.195553+00:00 app[headless-client.1]: 	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
2017-04-21T01:33:31.195620+00:00 app[headless-client.1]: 	at com.squareup.okhttp.Call.execute(Call.java:79)
2017-04-21T01:33:31.195688+00:00 app[headless-client.1]: 	at org.whispersystems.signalservice.internal.push.PushServiceSocket.getConnection(PushServiceSocket.java:610)
2017-04-21T01:33:31.195767+00:00 app[headless-client.1]: 	... 5 more
2017-04-21T01:33:31.195955+00:00 app[headless-client.1]: Caused by: sun.security.validator.ValidatorException: PKIX path building failed: java.security.cert.CertPathBuilderException: No issuer certificate for certificate in certification path found.
2017-04-21T01:33:31.203907+00:00 app[headless-client.1]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
2017-04-21T01:33:31.203967+00:00 app[headless-client.1]: 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
2017-04-21T01:33:31.204034+00:00 app[headless-client.1]: 	at sun.security.validator.Validator.validate(Validator.java:260)
2017-04-21T01:33:31.204093+00:00 app[headless-client.1]: 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
2017-04-21T01:33:31.204168+00:00 app[headless-client.1]: 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
2017-04-21T01:33:31.204230+00:00 app[headless-client.1]: 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)
2017-04-21T01:33:31.204295+00:00 app[headless-client.1]: 	at org.whispersystems.signalservice.internal.util.BlacklistingTrustManager.checkServerTrusted(BlacklistingTrustManager.java:86)
2017-04-21T01:33:31.204641+00:00 app[headless-client.1]: 	at sun.security.ssl.AbstractTrustManagerWrapper.checkServerTrusted(SSLContextImpl.java:984)
2017-04-21T01:33:31.204715+00:00 app[headless-client.1]: 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1496)
2017-04-21T01:33:31.204767+00:00 app[headless-client.1]: 	... 24 more
2017-04-21T01:33:31.205084+00:00 app[headless-client.1]: Caused by: java.security.cert.CertPathBuilderException: No issuer certificate for certificate in certification path found.
2017-04-21T01:33:31.205153+00:00 app[headless-client.1]: 	at org.spongycastle.jce.provider.PKIXCertPathBuilderSpi.engineBuild(PKIXCertPathBuilderSpi.java:127)
2017-04-21T01:33:31.205206+00:00 app[headless-client.1]: 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
2017-04-21T01:33:31.205265+00:00 app[headless-client.1]: 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
2017-04-21T01:33:31.205321+00:00 app[headless-client.1]: 	... 32 more
2017-04-21T01:33:31.205445+00:00 app[headless-client.1]: Error loading state file "store/data/0x85eec6286c17f8071015b5a9dc1050c44a47a73d"

```

**Comment by faymontage** [comment]
This is due to using old service URLs whose SSL certificate no longer matched the one the headless client is pinned to. This is fixed by b3a95f49174661843dc98faee55e5e72e52341ca which corrects the service URLs and begins explicitly defining the version of headless client to use. 👏
